version: '3.4'
services:
  htz_promotions_react:
    hostname: htz-promotions-app
    build:
      context: .
      dockerfile: Dockerfile-promotions
      args:
        NEXT_BUILD_ID: ${version:-latest}
    image: 'nexus-ng.themarker.com/htz-promotions-app:${version:-latest}'
    ports:
      - 2004:2004
    deploy:
      replicas: 3
      update_config:
        parallelism: 3
        delay: 30s
        order: start-first
      restart_policy:
        condition: on-failure
    environment:
      - NODE_ENV=production
      - CONNECTION_PRESET=stage
      - NEXT_BUILD_ID=${NEXT_BUILD_ID:-latest}
      # the following environment is optional
      - PORT=2004
      - BIND_ADDRESS=promotions
      - HOSTNAME=promotions
      - GRAPHQL_USE_SSL=true
      - GRAPHQL_EXPOSE_PORT=false

    networks:
      - prod01

networks:
  prod01:
    external: true
