version: "3.3"
services:
  htz_react:
    build: .
    image: "docker.themarker.com:8083/htz-front-app:${version:-latest}"
    ports:
      - 2100:2100
    environment:
      - NODE_ENV=dev
      - CONNECTION_PRESET=dev
      - NEXT_BUILD_ID=${BUILD_ID:-LATEST}
      # the following environment is optional
      - PORT=2100
      - BIND_ADDRESS=ms-apps
      - HOSTNAME=docker
      - GRAPHQL_USE_SSL=false
      - GRAPHQL_EXPOSE_PORT=true

