version: '3.4'
services:
  htz_promotions_react:
    hostname: htz-promotions-app
    build:
      context: .
      dockerfile: Dockerfile-promotions
      args:
        NEXT_BUILD_ID: ${version:-latest}
    image: 'nexus-ng.themarker.com/htz-promotions-app:${version:-latest}'
    ports:
      - 2034:2034
    environment:
      - NODE_ENV=production
      - CONNECTION_PRESET=dev
      - NEXT_BUILD_ID=${NEXT_BUILD_ID:-latest}
      # the following environment is optional
      - PORT=2034
      - BIND_ADDRESS=dev-promotions
      - HOSTNAME=dev-promotions
      - GRAPHQL_USE_SSL=true
      - GRAPHQL_EXPOSE_PORT=false
      - GRAPHQL_SUB_DOMAIN=graphql-stage

    networks:
      - prod01

networks:
  prod01:
    external: true
