version: "3.3"
services:
  htz_react:
    build: .
    hostname: htz-front-app
    #command: ["yarn", "workspace", "@haaretz/haaretz.co.il", "start"]
    image: "docker.themarker.com:8083/htz-front-app:${version:-latest}"
    ports:
      - 2000:2000
    environment:
      - NODE_ENV=production
      - CONNECTION_PRESET=prod
      - NEXT_BUILD_ID=${BUILD_ID:-LATEST}
      # the following environment is optional
      - PORT=2000
      - BIND_ADDRESS=react-prod
      - HOSTNAME=react-prod
      - GRAPHQL_USE_SSL=true
      - GRAPHQL_EXPOSE_PORT=false

    networks:
      - prod01

networks:
  prod01:
    external: true

