version: "3.4"
services:
  htz_react:
    build: .
    hostname: htz-front-app
    #command: ["yarn", "workspace", "@haaretz/haaretz.co.il", "start"]
    image: "docker.themarker.com:8083/htz-front-app:${version:-latest}"
    ports:
      - 2500:2500
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2500/1.6318504"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 5
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure

    environment:
      - NODE_ENV=production
      - CONNECTION_PRESET=prod
      - NEXT_BUILD_ID=${version:-latest}
      # the following environment is optional
      - PORT=2500
      - BIND_ADDRESS=www
      - HOSTNAME=www
      - GRAPHQL_USE_SSL=true
      - GRAPHQL_EXPOSE_PORT=false

    networks:
      - prod01

networks:
  prod01:
    external: true

