version: "3.3"
services:
  htz_react:
    hostname: htz-front-app
    build: .
    image: "docker.themarker.com:8083/htz-front-app:${version:-latest}"
    ports:
      - 2200:2200
    environment:
      - NODE_ENV=production
      - CONNECTION_PRESET=stage
      - NEXT_BUILD_ID=${BUILD_ID:-LATEST}"
      # the following environment is optional
      - PORT=2200
      - BIND_ADDRESS=stg-ms-apps
      - HOSTNAME=stg-ms-apps
      - GRAPHQL_USE_SSL=false
      - GRAPHQL_EXPOSE_PORT=true


    networks:
      - prod01

networks:
  prod01:
    external: true

