version: "3.4"
services:
  htz_react:
    build: 
     context: .
     args:
        NEXT_BUILD_ID: ${version:-latest}
    hostname: htz-front-app
    #command: ["yarn", "workspace", "@haaretz/haaretz.co.il", "start"]
    image: "docker.themarker.com:8083/htz-front-app:${version:-latest}"
    ports:
      - 2000:2000
    #healthcheck:
    #  test: ["CMD", "curl", "-f", "http://localhost:2000/1.6318504"]
    #  interval: 10s
    #  timeout: 5s
    #  retries: 3
    deploy:
      replicas: 5
      update_config:
        parallelism: 5
        delay: 30s
        #order: start-first
      restart_policy:
        condition: on-failure

    environment:
      - NODE_ENV=production
      - CONNECTION_PRESET=prod
      - NEXT_BUILD_ID=${NEXT_BUILD_ID:-latest}
      # the following environment is optional
      - PORT=2000
      - PM2_PUBLIC_KEY=1pu5b2hg3lk4y1b
      - PM2_SECRET_KEY=2sffny3viue6z15
      - BIND_ADDRESS=react-prod
      - HOSTNAME=react-prod
      - GRAPHQL_USE_SSL=true
      - GRAPHQL_EXPOSE_PORT=false

    networks:
      - prod01

networks:
  prod01:
    external: true

