const types = new Map([
  [ 'com.htz.MagazineArticleQuote', 'Quote', ],
  [ 'com.htz.PageMainBlockElement', 'MainBlock', ],
  [ 'com.htz.magazineArticleDfpBannerElement', 'DfpBanner', ],
  [ 'com.polobase.ClickTrackerBannersWrapper', 'ClickTrackerBannersWrapper', ],
  [ 'com.polobase.DfpBannerElement', 'DfpBanner', ],
  [ 'com.polobase.quickNewsletterRegistration', 'MobileQuickRegistrationType', ],
  [ 'com.polobase.whtzMobileSiteListsWrapper', 'MobileListWrapper', ],
  [ 'com.tm.BlogImage', 'Image', ],
  [ 'com.tm.element.List', 'List', ],
  [ 'com.tm.ElementGroup', 'ElementGroup', ],
  [ 'com.tm.GridElementGroup', 'GridElementGroup', ],
  [ 'com.tm.HeaderNewsGroup', 'HeaderNewsGroup', ],
  [ 'com.tm.HtmlElement', 'HtmlElement', ],
  [ 'com.tm.Image', 'Image', ],
  [ 'com.tm.ImageGalleryElement', 'ImageGallery', ],
  [ 'com.tm.Link', 'Link', ],
  [ 'com.tm.TabViewElement', 'TabViewElement', ],
  [ 'com.tm.TableScore', 'TableScore', ],
  [ 'com.tm.Video', 'Video', ],
  [ 'com.tm.element.List', 'List', ],
  [ 'com.tm.newsLetterQuickRegistrationRespAuto', 'NewsLetter', ],
  [ 'com.tm.promotion.banner.MiddleRuler', 'MiddleRuller', ],
  [ 'com.tm.ExternalRssElement', 'RssFeed', ],
  [ 'embed', 'Embed', ],
  [ 'error', 'NullFallback', ],
  [ 'gallery', 'ImageGallery', ],
  [ 'image', 'Image', ],
  [ 'interactiveElement', 'Interactive', ],
  [ 'linksBlock', 'SeriesOrBlockArticles', ],
  [ 'paragraph', 'Paragraph', ],
  [ 'relatedArticleSeries', 'SeriesOrBlockArticles', ],
  [ 'relatedArticles', 'RelatedArticles', ],
  [ 'tagsElement', 'Tags', ],
  [ 'video', 'Video', ],
]);

export default inputTemplate => types.get(inputTemplate);
