version: "3.3"
services:
  htz_react:
    hostname: promotions-page
    build: .
    #command: ["yarn", "workspace", "@haaretz/haaretz.co.il", "start"]
    image: "docker.themarker.com:8083/promotions-page:${version:-latest}"
    ports:
      - 2004:2004
    environment:
      - NODE_ENV=production
      - CONNECTION_PRESET=prod
      - NEXT_BUILD_ID=${BUILD_ID:-LATEST}
      # the following environment is optional
      - PORT=2004
      - BIND_ADDRESS=promotions
      - HOSTNAME=promotions
      - GRAPHQL_USE_SSL=true
      - GRAPHQL_EXPOSE_PORT=false

    networks:
      - prod01

networks:
  prod01:
    external: true

