version: "3.3"
services:
  htz_react:
    hostname: promotions-page
    commans:["yarn", "workspace", "@haaretz/purchase-page", "start"]
    build: .
    image: "docker.themarker.com:8083/promotions-page:${version:-latest}"
    ports:
      - 2201:2201
    environment:
      - NODE_ENV=production
      - CONNECTION_PRESET=stage
      - NEXT_BUILD_ID=${BUILD_ID:-LATEST}"
      # the following environment is optional
      - PORT=2201
      - BIND_ADDRESS=ppromotions
      - HOSTNAME=ppromotions
      - GRAPHQL_USE_SSL=true
      - GRAPHQL_EXPOSE_PORT=false

    networks:
      - prod01

networks:
  prod01:
    external: true


