version: '3.3'
services:
  htz_react:
    hostname: promotions-page
    build: .
    #command: ["yarn", "workspace", "@haaretz/haaretz.co.il", "start"]
    image: 'nexus-ng.themarker.com/ppromotions-page:${version:-latest}'
    ports:
      - 2002:2002
    environment:
      - NODE_ENV=production
      - CONNECTION_PRESET=stage
      - NEXT_BUILD_ID=${BUILD_ID:-LATEST}
      # the following environment is optional
      - PORT=2002
      - BIND_ADDRESS=ppromotions
      - HOSTNAME=ppromotions
      - GRAPHQL_USE_SSL=true
      - GRAPHQL_EXPOSE_PORT=false

    networks:
      - prod01

networks:
  prod01:
    external: true
